version: '3'

services:
  server:
    container_name: NODEJS_SERVER
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '8888:8888'
    networks:
      - network1
      
      
  nginx:
       build:
            context: ./nginx
       container_name: nginx
       hostname: nginx
       ports :
            - "80:80"
       depends_on:
            - server
       networks:
            - network1

  db:
    image: 'mongo'
    container_name: MONGODB
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
    networks:
            - network1
      
networks:
    network1:
        external: false
      
